spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        health-check-interval: 30s
      config:
        enabled: true
        format: YAML
        prefix: configuration
        default-context: application
  application:
    name: stock-service
  config:
    import: optional:consul:localhost/8500
  datasource:
    url: jdbc:postgresql://localhost:5432/stockdb
    username: stock-service
    password: stock-service
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.cloud.consul: DEBUG

kafka:
  bootstrapAddress: localhost:9092
